### ISSUE TITLE
Summary of Immediate needs

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/explorer#1] opened 2016-07-30 21:22 UTC
I went through the code and it's pretty bare, just looking up address/blocks/tx with web3 calls. So there's a lot of work to do. I'm starting this as a task list so we can organize what we're working on.

**Server**
- Miner stats
  - ID'ing miner from input data
- Contracts: View internal txs

**Client**
- Miner stats
  - Show Mined blocks/uncles ([similar to etherscan](http://etherscan.io/address/0x2a65aca4d5fc5b5c859090a6c34d164135398226#internaltx))
- Make it less ugly

**Comment by madmanblues** [comment] 2016-07-30 21:40
Count on me!

**Comment by matthewjamesr** [comment] 2016-07-31 17:26
@elaineo Added search field to the task list. As for the db, what are you thinking? Mongo?

**Comment by elaineo** [comment] 2016-07-31 18:46
Yeah, I was gonna go with Mongodb unless there are any objections.

**Comment by whatsdis** [comment] 2016-08-01 06:39
are there any alternatives to mongodb? is a SQL db out of the question?

**Comment by elaineo** [comment] 2016-08-01 06:56
geth uses LevelDB to store the blockchain, which is a key-value store, so SQL wouldn't make sense. I'm open to other NoSQL options though.

**Comment by whatsdis** [comment] 2016-08-01 07:10
Just a minor thing but based on postings on HN in the past, MongoDB hasn't got a stellar review from people using it in high scale production....but not sure how true that is I've never had to deal with high scale situations.

RethinkDB comes to mind seems to have real time stuff built in on their landing page https://www.rethinkdb.com/

**Comment by elaineo** [comment] 2016-08-01 08:06
I'm not familiar with any of those, I was just going with what would be quickest to get a db fully populated and running. If you want to do some research and let us know your recommendations that would be great!

**Comment by whatsdis** [comment] 2016-08-01 16:39
Let's use whatever will get us running quickest.

**Comment by realcodywburns** [comment] 2016-08-02 23:24
Im in, ill start digging around and see what i can work out UX/UI side.

**Comment by whatisgravity** [comment] 2016-08-03 03:50
Do you need funding for a server to host an example of the explorer? @arvicco May be willing to forward the DNS of explore.ethereumclassic.org too once the project surpasses the features of the existing open source explorer.

**Comment by elaineo** [comment] 2016-08-03 03:54
I have it hosted on an ec2 instance, the cost is no big deal for now. right now I'm just populating the db so there's some downtime.  
@whatisgravity unrelated -- do you still need someone to fork and modify the python client?

**Comment by whatisgravity** [comment] 2016-08-03 04:32
It was just started by a new volunteer today, I have not investigated the project so I'm not sure how much has been done. Were you thinking about using that client to interface with the network? From what I understand Parity preforms well in benchmarks.

**Comment by elaineo** [comment] 2016-08-03 04:48
No, I use geth, I haven't tried Parity. Just asking about the py clients, since I thought they had not been accounted for.

**Comment by whatisgravity** [comment] 2016-08-03 05:19
There are two components to the pyclient, pyethereum has been started, more details can be found in the volunteer thread. If you are able to, it would be nice to have others help.

**Comment by masonicGIT** [comment] 2016-08-03 06:06
+1 for avoiding mongoDB, its a bit difficult to deal with big ints. I'd recommend postgres.

If it helps, I'm happy to build javascript wrappers while I'm building this up https://github.com/masonicGIT/ethereum-api.

Would be great to plug into the database for better queries.

**Comment by elaineo** [comment] 2016-08-03 06:55
@masonicGIT I already have a good chunk of the blockchain in db so i'd rather just get something up and functional, and switch to psql later if this turns out to have limitations.

**Comment by whatisgravity** [comment] 2016-08-03 07:03
I'm not suggesting it is the best example for proper design or even secure design, but mongo does appear to be used in Mist. 

They may have solved the issues with bigints. It may be worth researching the solution they used for this because it may be good. (https://github.com/ethereumproject/meteor-package-accounts/blob/master/accounts.js) 

I just glanced over it but I believe they just converted it to a string.

**Comment by kimisan** [comment] 2016-08-03 07:22
@elaineo  @whatisgravity 
I am about to design some d3.js chart module for ETC explorer, like hash rate distribution.
Ask for your recommendation.

**Comment by gcmartinelli** [comment] 2016-08-03 10:42
Guys, is this live? May I suggest it get's pushed even with limited features? We really need a block explorer even with the minimum specs (search, IMO).

**Comment by whatisgravity** [comment] 2016-08-03 11:37
@gcmartinelli Are you able to host a version? I believe they are basing it on an open source explorer which already exists but has very limited features.

**Comment by julian1** [comment] 2016-08-03 12:03
why is a db needed? the state is maintained by the client - eg leveldb or whatever geth uses?

**Comment by whatisgravity** [comment] 2016-08-03 13:25
@julian1 LevelDB also being used by multiple processes would run into locking issues due to the nature of the DB.  Because of this and the fact there are better designed databases for the use case of a lot of reads and few writes expected from a web application.

**Comment by elaineo** [comment] 2016-08-03 17:35
Yes, I'm storing the bigints as strings in MongoDB.

Okay, sounds like there is pressing need for a better explorer. I'll pause the DB-syncing for a bit and get what we have up live today. It's unlikely that people will be searching through months-old transactions anyway.

@matthewjamesr @realcodywburns et al -- what are your thoughts on the front end? I think it could use an entire new face, though maybe I'll just add in some fields to show tx details for now.

@masonicGIT I can expose some APIs for you, do you want just basic tx/addr/block queries?

**Comment by matthewjamesr** [comment] 2016-08-03 17:47
@elaineo let's keep it angular and use materiaizecss to stay organized for styles. We can carry this framework through all of our ported web-apps, etc, to denote it is a ETC site.

**Comment by whatsdis** [comment] 2016-08-03 19:20
I'll be happy to take on Python work as well, please guide me to the right channel.

**Comment by whatisgravity** [comment] 2016-08-03 19:24
@whatsdis Check out https://github.com/ethereumproject/pyethereum

**Comment by elaineo** [comment] 2016-08-03 19:57
@kimisan so we'll have data like this: https://etherchain.org/statistics/miners
It may be helpful to have a chart like this: https://etherscan.io/charts/hashrate

**Comment by kimisan** [comment] 2016-08-03 20:15
@elaineo , wow! got it!
I will prepare a D3.js chart moduel for this explorer.
But where I can commit and  push the code, new folder of this repo or new repo ?

**Comment by elaineo** [comment] 2016-08-03 20:41
Same repo, do a pull request. You can just have it be a standalone page for
now, I'll provide an endpoint for the data.

**Comment by masonicGIT** [comment] 2016-08-03 21:08
@elaineo - If you have the ability to do a tx list for an account or to view internal transactions it would be great to have access to those :-)

**Comment by kimisan** [comment] 2016-08-03 21:17
@elaineo  Ok, got it. For the hashrate chart, api of https://etherchain.org/statistics/miners , it only show currently hashrate, not a time-series dataset/array.  I will keep push/record hashrate data to my mongodb server.

**Comment by elaineo** [comment] 2016-08-03 23:15
These are the API endpoints that the server currently supports. See app.js for data format.

app.post('/addr', routes.addr);
app.post('/tx', routes.tx);
app.post('/block', routes.block);

BTW, so far I've been pushing all changes directly to master. I'm about to start changing client-side stuff to display transactions & info, so if anyone is working on the frontend, LMK and I'll do a PR for further updates.

PS. I'm gonna stop annoying everyone in this thread and instead post updates to the Explorer slack channel I just created.

**Comment by Empty2k12** [comment] 2016-08-04 11:46
Mobile layout looks like :poop:, will tackle that if someone tell me how the design should look/what the future plans for it are.

**Comment by MaffeProg** [comment] 2016-08-04 21:34
Any need for help here? I am able to help

**Comment by elaineo** [comment] 2016-08-04 21:50
Yes! @Empty2k12 @MaffeProg Basically I suck at front end stuff... there's a rough sketch of what probably needs to be made available in the dropdown menus here: http://blocks.elaineou.com/home

Right now I'm building the backend pieces and just dumping data onto the page, and it would be super helpful if someone could create front end templates that can receive data.

**Comment by elaineo** [comment] 2016-08-05 09:27
Okay, the block explorer is more or less functional now. The dropdown menus on the page don't actually work, but they represent a sort of TODO list for next tasks.

http://blocks.elaineou.com/home

**Comment by Empty2k12** [comment] 2016-08-05 10:01
@elaineo I'm going to crunch some CSS now, improving the desktop size and hopefully making a accessible mobile site. Stay tuned!

**Comment by Empty2k12** [comment] 2016-08-05 10:54
@elaineo I am in the process of fixing a couple CSS things with the layout. Here I have a screenshot of the overhauled Transactions History Box. Is this style something you like which I should continue?

![overhauled_txhistory](https://cloud.githubusercontent.com/assets/6954968/17434585/9073c196-5b0b-11e6-95d8-c159630110c7.PNG)

**Comment by matthewjamesr** [comment] 2016-08-05 13:33
@Empty2k12 Good job on the box styling, thanks for cleaning up the overflow scrollbar.

**Comment by elaineo** [comment] 2016-08-05 15:35
@Empty2k12 Yep looks great! If you do a pull request I can merge it, or you can just push the changes.

**Comment by Empty2k12** [comment] 2016-08-05 16:02
I will create a pull request when I'm done refining the front page. Which
specific feature needs a template most first? Will create that then.

**Comment by elaineo** [comment] 2016-08-05 17:38
It's up to you. The current address/block/tx pages are a pretty ugly. 

Next thing to do is add some fields to the address pages to support contract source/viewing/validation.

In the back, I'm working on making the db queries faster and add some error handling, then I'll build the libraries for the Contract Addresses

**Comment by matthewjamesr** [comment] 2016-08-05 20:48
@elaineo now that it is the weekend I can lend a hand either front or backend. What prominent need can I help with?

**Comment by elaineo** [comment] 2016-08-05 21:05
@matthewjamesr After I make the DB less crappy, I think the two biggest things are 

- handling contract addresses 
  - view internal txs
  - view/validate bytecode
- Miner stats
  - ID'ing miner from input data
  - Show Mined blocks/uncles ([similar to etherscan](http://etherscan.io/address/0x2a65aca4d5fc5b5c859090a6c34d164135398226#internaltx))

Though that's just my opinion, there may be more urgent things that other people want.

**Comment by matthewjamesr** [comment] 2016-08-05 22:04
I have been comparing against gastracker and indeed our explorer is slacking in terms of quickly showing confirmed transactions. I am sure this is because of the in-development nature but I just wanted to make everyone aware.

**Comment by elaineo** [comment] 2016-08-05 22:13
@matthewjamesr It's true. I wasn't sure whether a web3 listener constantly updating with each new block would degrade performance too much. Maybe @splix can shed some light on this for gastracker?

**Comment by matthewjamesr** [comment] 2016-08-05 22:20
@elaineo I think a better way would just have a intermediary app synching geth data to mongo

1. geth rpc
2. synch app streams data from geth, mutates to what we want to actually retain, inserts into mongo.
3. Explorer removes web3 and just pings mongo.

Thoughts?

**Comment by Empty2k12** [comment] 2016-08-05 22:26
@matthewjamesr also offering a WEBSOCKET API for different events would be good.

1. The Explorer could add new blocks when they are broadcasted to the networks (similar to the way blockchain.info-Explorer/API works)
2. Developer could tap in and create applications by using this abstraction from the blockchain (similar to (my service) https://txwat.ch/ which offers integration with the blockchain without having to use bitcoind)

**Comment by matthewjamesr** [comment] 2016-08-05 22:29
@Empty2k12 would be great but that should be a V2 feature :).

**Comment by elaineo** [comment] 2016-08-05 22:34
@matthewjamesr removing web3 makes sense for blocks, possibly also transactions, but for address info I think it's faster to get the balance via web3, rather than try to calculate it from all the txs.

**Comment by jdc4429** [comment] 2016-08-07 23:00
Can you add the difficulty  please.  In a way you can copy/paste.

**Comment by elaineo** [comment] 2016-08-07 23:45
@jdc4429 already there: http://blocks.elaineou.com/block/2028786

**Comment by comndkn** [comment] 2016-08-15 07:54
Hi All, do you think GPU mining of ETC will remain feasible till December of 2016? When can I expect hashing difficulty to rise in the near term?

**Comment by iquidus** [comment] 2016-09-15 13:50
Hi everyone, 

I'm the lead dev of iquidus explorer, used by a very large number of bitcoin based alts. I'm pretty keen to help out on this project, there's a few things i want to take care of not mentioned here, all backend related, will submit some pull requests once i have tested throughly. Then start getting my hands dirty with more feature based changes.

**Comment by elaineo** [comment] 2016-09-15 15:31
@iquidus thanks!

**Comment by pyskell** [comment] 2018-04-27 19:47
This issue seems outdated, closing

**Closed by pyskell** 2018-04-27 19:47 UTC
